name: Tag Release Upload
author: Jason Davis, Dot HQ
description: Creates a tag, release, and uploads assets based on the version string specified

inputs:
  github-token:
    required: true
    description: secrets.GITHUB_TOKEN, or a token with read/write access to the repo
    
  version: 
    required: true
    description: Version to create
    
  name: 
    description: Name of release
    
  body_path: 
    description: Path to a file that is the body of the release
    
  assets:
    description: json string array of assets paths to upload to the release. E.G. '[ "win-x64.zip", "linux-x24.zip" ]'
    
  overwrite:
    description: bool value to overwrite assets
  
runs:
  using: node12
  main: index.js

branding:
    icon: activity
    color: gray-dark
