name: Tag and Release
author: Jason Davis
description: Creates a tag (if not exists), release (if not exists), uploads assets (if not exists), and publishes to nuget.dev (if not exists) based on the version string specified

inputs:
  github-token:
    required: true
    description: secrets.GITHUB_TOKEN, or a token with read/write access to the repo
    
  version: 
    required: true
    description: Version to create
    
runs:
  using: node12
  main: index.js