name: Tag and Release and Upload
author: Jason Davis
description: Creates a tag, release, and uploads assets based on the version string specified

inputs:
  github-token:
    required: true
    description: secrets.GITHUB_TOKEN, or a token with read/write access to the repo
    
  version: 
    required: true
    description: Version to create
    
  assets:
    description: json string array of assets paths to upload to the release. E.G. '[ "win-x64.zip", "linux-x24.zip" ]'
  
runs:
  using: node12
  main: index.js
