name: "Test the action"
on:
  push:
    branches: 
      - master

jobs:
  
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Test Action
      uses: ./
      env:
        ACTIONS_STEP_DEBUG: true
      with:
        version: v1.0.0
        github-token: ${{ secrets.GITHUB_TOKEN }}
        assets: '[ "LICENSE", "README.md" ]          