name: "Test the action"
on:
  push:
    branches: 
      - master

jobs:
  
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Test Action
      uses: ./
      with:
        version: 1.0.0
        github-token: ${{ secrets.GITHUB_TOKEN }}
        